import 'dart:convert';

import 'package:drift/drift.dart';
import 'package:flutter/services.dart' show AssetBundle, rootBundle;
import 'package:isi_steel_sales_mobile/core/database/drift/app_database.dart';
import 'package:isi_steel_sales_mobile/core/error/exceptions.dart';

/// The bundled gazetteer, and the code that gets it into the database.
///
/// ## Where the asset comes from
///
/// `assets/geo/kh_geo_seed_v1.json`, generated by `tool/geo/build_geo_seed.py`
/// from the NCDD administrative hierarchy and Cambodia Post's commune postal
/// codes. Regenerating it is a deliberate, reviewable step — the script prints
/// the postal-code match rate so a drop in coverage shows up in the diff rather
/// than on a rep's handset.
///
/// ## Why the keys are one letter
///
/// `c`/`p`/`en`/`km`/`u`/`z`. Long keys would add roughly 900 KB to a file that
/// is repeated 16,000 times, which is app size and parse time spent on
/// self-documentation that belongs — and lives — in this class and in
/// `docs/features/geo-location/architecture.md`.
class GeoSeedAssetLoader {
  const GeoSeedAssetLoader({AssetBundle? bundle}) : _bundle = bundle;

  final AssetBundle? _bundle;

  /// Injectable so a test can seed from a small fixture instead of the real
  /// 1.3 MB asset. `rootBundle` is resolved lazily rather than in the
  /// constructor because touching it requires a Flutter binding, and the DI
  /// container is built before one exists in some entry points.
  AssetBundle get _assets => _bundle ?? rootBundle;

  static const String assetPath = 'assets/geo/kh_geo_seed_v1.json';

  /// Parses the asset into Drift companions, ready for one batched insert.
  ///
  /// Returns companions rather than writing them so the caller owns the
  /// transaction — the DAO's `replaceAll` has to delete and insert atomically,
  /// and a loader that wrote its own rows could not participate in that.
  Future<GeoSeedData> load() async {
    final String raw;
    try {
      raw = await _assets.loadString(assetPath);
    } catch (_) {
      // A missing asset is a packaging error, not a runtime condition. Say so
      // precisely: "no provinces found" would send someone looking at the
      // database.
      throw const CacheException(
        message: 'Geo seed asset is missing from the bundle.',
      );
    }

    final Map<String, dynamic> doc;
    try {
      doc = json.decode(raw) as Map<String, dynamic>;
    } on FormatException catch (e) {
      throw CacheException(message: 'Geo seed asset is not valid JSON: $e');
    }

    List<Map<String, dynamic>> rows(String key) =>
        ((doc[key] as List?) ?? const []).cast<Map<String, dynamic>>();

    final provinces = rows('provinces');
    if (provinces.isEmpty) {
      throw const CacheException(
        message: 'Geo seed asset contains no provinces.',
      );
    }

    return GeoSeedData(
      version: (doc['version'] as num?)?.toInt() ?? 0,
      provinces: [
        for (final r in provinces)
          GeoProvincesCompanion.insert(
            code: r['c'] as String,
            nameEn: r['en'] as String,
            nameKm: r['km'] as String,
            unit: r['u'] as String,
          ),
      ],
      districts: [
        for (final r in rows('districts'))
          GeoDistrictsCompanion.insert(
            code: r['c'] as String,
            provinceCode: r['p'] as String,
            nameEn: r['en'] as String,
            nameKm: r['km'] as String,
            unit: r['u'] as String,
          ),
      ],
      communes: [
        for (final r in rows('communes'))
          GeoCommunesCompanion.insert(
            code: r['c'] as String,
            districtCode: r['p'] as String,
            // Derived, not stored, because it is already the first two digits
            // of the commune code by construction. Storing it in the asset too
            // would be 1,646 chances for the two to disagree.
            provinceCode: (r['c'] as String).substring(0, 2),
            nameEn: r['en'] as String,
            nameKm: r['km'] as String,
            unit: r['u'] as String,
            postalCode: Value(r['z'] as String?),
          ),
      ],
      villages: [
        for (final r in rows('villages'))
          GeoVillagesCompanion.insert(
            code: r['c'] as String,
            communeCode: r['p'] as String,
            nameEn: r['en'] as String,
            nameKm: r['km'] as String,
          ),
      ],
    );
  }
}

/// One parsed gazetteer, ready to insert.
class GeoSeedData {
  const GeoSeedData({
    required this.version,
    required this.provinces,
    required this.districts,
    required this.communes,
    required this.villages,
  });

  final int version;
  final List<GeoProvincesCompanion> provinces;
  final List<GeoDistrictsCompanion> districts;
  final List<GeoCommunesCompanion> communes;
  final List<GeoVillagesCompanion> villages;
}
