import 'dart:io';

/// Writes `ios/Flutter/Env.xcconfig` from the repo-root `.env`.
///
/// Run with: `dart run tool/generate_ios_env.dart`
///
/// ## Why this exists
///
/// The Google Maps iOS key used to be a string literal in `AppDelegate.swift`,
/// which put it in git history (`docs/SECURITY.md` §9 forbids exactly this).
/// Android solves the same problem with a Gradle manifest placeholder; iOS has
/// no equivalent hook, so the key travels:
///
/// ```
/// .env  →  Env.xcconfig  →  $(GOOGLE_MAPS_API_KEY)  →  Info.plist
///       →  Bundle.main.object(forInfoDictionaryKey:)  →  GMSServices
/// ```
///
/// `Env.xcconfig` is git-ignored. Run this before `flutter build ios` locally,
/// and as a CI step before the iOS build (populating `.env` from GitHub
/// Secrets first).
///
/// This only handles values the *native* layer needs. Everything the Dart layer
/// reads goes through Envied (`lib/core/config/env.dart`) instead.
void main(List<String> args) {
  final envFile = File('.env');
  if (!envFile.existsSync()) {
    stderr.writeln(
      'ERROR: .env not found at ${envFile.absolute.path}\n'
      'Copy one of .env.development / .env.staging / .env.production to .env '
      'first, or populate it from CI secrets.',
    );
    exitCode = 1;
    return;
  }

  final values = _parseDotenv(envFile.readAsLinesSync());
  final mapsKey = values['GOOGLE_MAPS_IOS_KEY'] ?? '';

  if (mapsKey.isEmpty) {
    // Warn rather than fail: a build without maps is still a useful build, and
    // AppDelegate degrades gracefully when the key is absent.
    stderr.writeln(
      'WARNING: GOOGLE_MAPS_IOS_KEY is empty in .env — map tiles will not '
      'render in this build.',
    );
  }

  final out = File('ios/Flutter/Env.xcconfig');
  out.parent.createSync(recursive: true);
  out.writeAsStringSync(
    '// GENERATED by tool/generate_ios_env.dart — DO NOT EDIT, DO NOT COMMIT.\n'
    '// Source: .env (APP_ENV=${values['APP_ENV'] ?? 'unknown'})\n'
    'GOOGLE_MAPS_API_KEY=$mapsKey\n',
  );

  stdout.writeln('Wrote ${out.path} (APP_ENV=${values['APP_ENV'] ?? 'unknown'})');
}

/// Minimal `.env` reader: `KEY=VALUE`, ignoring blank lines and `#` comments.
///
/// Deliberately does not handle quoting or interpolation — the `.env` files in
/// this repo are flat literals, and a partial implementation of shell quoting
/// would be worse than none.
Map<String, String> _parseDotenv(List<String> lines) {
  final result = <String, String>{};
  for (final raw in lines) {
    final line = raw.trim();
    if (line.isEmpty || line.startsWith('#')) continue;

    final separator = line.indexOf('=');
    if (separator <= 0) continue;

    result[line.substring(0, separator).trim()] =
        line.substring(separator + 1).trim();
  }
  return result;
}
