import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:isi_steel_sales_mobile/core/database/drift/app_database.dart';
import 'package:isi_steel_sales_mobile/features/geo_location/data/datasources/geo_local_data_source.dart';
import 'package:isi_steel_sales_mobile/features/geo_location/data/datasources/geo_seed_asset_loader.dart';
import 'package:isi_steel_sales_mobile/features/geo_location/domain/entities/geo_unit.dart';

/// Imports the **real** `assets/geo/kh_geo_seed_v1.json` into a real database.
///
/// This is the test that would catch a regenerated gazetteer that lost half its
/// villages, gained a district whose code does not sit under its province, or
/// shipped a postal code that is not six digits — none of which the fixture
/// tests can see, because they use a fixture. It is the slowest test in the
/// feature and the only one that justifies the cost.
void main() {
  // `loadString` on rootBundle needs the binding, and the asset is only on the
  // test bundle's manifest once it is declared in pubspec.
  TestWidgetsFlutterBinding.ensureInitialized();

  late AppDatabase db;
  late GeoDriftLocalDataSource source;

  setUpAll(() async {
    db = AppDatabase(NativeDatabase.memory());
    source = GeoDriftLocalDataSource(db.geoDao, const GeoSeedAssetLoader());
    await source.seedIfEmpty();
  });

  tearDownAll(() => db.close());

  group('the bundled asset', () {
    test('imports the full national gazetteer', () async {
      final provinces = await source.childrenOf(GeoLevel.province, null);
      // 25 provinces is the count of Cambodia's administrative divisions since
      // Tbong Khmum was split off in 2013. A different number means the source
      // data changed and the assumption in the docs needs revisiting.
      expect(provinces.length, 25);
    });

    test('every province has at least one district', () async {
      final provinces = await source.childrenOf(GeoLevel.province, null);
      for (final p in provinces) {
        final districts = await source.childrenOf(GeoLevel.district, p.code);
        expect(districts, isNotEmpty, reason: 'province ${p.code} has none');
      }
    });

    test('Phnom Penh resolves down to a village with a postal code', () async {
      final districts = await source.childrenOf(GeoLevel.district, '12');
      expect(districts, isNotEmpty);

      final chamkarMon = districts.firstWhere((d) => d.code == '1201');
      expect(chamkarMon.name.en, 'Chamkar Mon');
      expect(chamkarMon.unit, 'Khan',
          reason: 'Phnom Penh is divided into khans, not districts');

      final communes = await source.childrenOf(GeoLevel.commune, '1201');
      final tonleBasak = communes.firstWhere((c) => c.code == '120101');
      expect(tonleBasak.unit, 'Sangkat');
      expect(tonleBasak.postalCode, isNotNull);

      final villages = await source.childrenOf(GeoLevel.village, '120101');
      expect(villages, isNotEmpty);
    });

    test('the capital is typed as a capital, a province as a province',
        () async {
      final provinces = await source.childrenOf(GeoLevel.province, null);
      expect(provinces.firstWhere((p) => p.code == '12').unit, 'Capital');
      expect(provinces.firstWhere((p) => p.code == '01').unit, 'Province');
    });

    test('every name is present in both languages', () async {
      final provinces = await source.childrenOf(GeoLevel.province, null);
      for (final p in provinces) {
        expect(p.name.en, isNotEmpty);
        expect(p.name.km, isNotEmpty);
      }
    });
  });

  group('structural integrity of the shipped data', () {
    test('every district code sits under its province code', () async {
      final provinces = await source.childrenOf(GeoLevel.province, null);
      for (final p in provinces) {
        for (final d in await source.childrenOf(GeoLevel.district, p.code)) {
          expect(d.isChildOf(p.code), isTrue,
              reason: 'district ${d.code} is not under province ${p.code}');
        }
      }
    });

    test('every commune and village code sits under its parent', () async {
      // One province is enough to prove the invariant without walking 14,372
      // villages four levels deep on every CI run; the codes are generated by
      // the same rule everywhere.
      for (final d in await source.childrenOf(GeoLevel.district, '12')) {
        for (final c in await source.childrenOf(GeoLevel.commune, d.code)) {
          expect(c.isChildOf(d.code), isTrue, reason: 'commune ${c.code}');
          for (final v in await source.childrenOf(GeoLevel.village, c.code)) {
            expect(v.isChildOf(c.code), isTrue, reason: 'village ${v.code}');
          }
        }
      }
    });

    test('every postal code that exists is six digits', () async {
      final sixDigits = RegExp(r'^\d{6}$');
      for (final d in await source.childrenOf(GeoLevel.district, '12')) {
        for (final c in await source.childrenOf(GeoLevel.commune, d.code)) {
          final code = c.postalCode;
          if (code == null) continue;
          expect(sixDigits.hasMatch(code), isTrue,
              reason: 'commune ${c.code} has postal code "$code"');
        }
      }
    });
  });

  group('seeding', () {
    test('is idempotent — a second call does not duplicate or re-import',
        () async {
      final before = await db.geoDao.provinceCount();
      await source.seedIfEmpty();
      expect(await db.geoDao.provinceCount(), before);
    });
  });

  group('search over real data', () {
    test('"Phnom" matches Phnom Penh', () async {
      final hits = await source.search(GeoLevel.province, null, 'Phnom');
      expect(hits.map((p) => p.code), contains('12'));
    });

    test('a Khmer query matches even though the UI language is irrelevant here',
        () async {
      final hits = await source.search(GeoLevel.province, null, 'ភ្នំពេញ');
      expect(hits.map((p) => p.code), contains('12'));
    });

    test('an empty query returns the unfiltered list', () async {
      final all = await source.childrenOf(GeoLevel.province, null);
      final searched = await source.search(GeoLevel.province, null, '   ');
      expect(searched.length, all.length);
    });

    test('district search filters within the province only', () async {
      final hits = await source.search(GeoLevel.district, '12', 'Chamkar');
      expect(hits, isNotEmpty);
      for (final d in hits) {
        expect(d.isChildOf('12'), isTrue);
      }
    });
  });

  group('guard rails', () {
    test('asking for children below province without a parent is an error',
        () async {
      // The UI locks these fields, so reaching here means a caller bug — and
      // silently reading the whole table would be far worse than throwing.
      expect(
        () => source.childrenOf(GeoLevel.district, null),
        throwsA(isA<ArgumentError>()),
      );
    });
  });
}
